# encoding=utf-8
## SOLVED 2013/12/20
## 76576500

# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
# ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28

# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred
# divisors?

import helpers.prime as prime

def euler ():
    i = 1
    triangle = 1
    # for each triangle number
    while True:
        # if the number has over 500 divisors
        if prime.divisor_count (triangle) > 500:
            # return it
            return triangle
        # continue to next triangle number
        i += 1
        triangle += i
